version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  labels:
  - "Dependencies \U0001F4E6"
  - "PHP \U0001F418"
  versioning-strategy: widen
  ignore:
  - dependency-name: wyrihaximus/async-test-utilities
    versions:
    - 3.4.10
    - 3.4.11
    - 3.4.12
    - 3.4.13
    - 3.4.14
    - 3.4.15
    - 3.4.16
    - 3.4.17
    - 3.4.18
    - 3.4.19
    - 3.4.21
    - 3.4.22
    - 3.4.23
    - 3.4.3
    - 3.4.4
    - 3.4.5
    - 3.4.6
    - 3.4.7
    - 3.4.8
    - 3.4.9
